# The package name, as it will appear on pub.dev.
# نام پکیج، همانطور که در pub.dev نمایش داده خواهد شد.
name: physicsal_navigation

# A short, catchy description of the package.
# توضیحی کوتاه و جذاب در مورد پکیج.
description: A beautiful, highly customizable, physics-based navigation bar for Flutter, featuring a throwable FAB with realistic physics and a stunning glassmorphic bottom bar.
# یک نوار ناوبری زیبا، کاملاً قابل سفارشی‌سازی و مبتنی بر فیزیک برای فلاتر، همراه با یک دکمه شناور قابل پرتاب با فیزیک واقع‌گرایانه و یک نوار پایین شیشه‌ای خیره‌کننده.

# The version of the package. Follow semantic versioning (major.minor.patch).
# نسخه پکیج. از نسخه‌بندی معنایی (major.minor.patch) پیروی کنید.
version: 1.0.1

# The homepage of the package, typically a link to the GitHub repository.
# صفحه اصلی پکیج، معمولاً لینکی به مخزن گیت‌هاب است.
homepage: https://github.com/ShoghShahadat/physicsal_navigation

# The repository where the package source code is located.
# مخزنی که کد منبع پکیج در آن قرار دارد.
repository: https://github.com/ShoghShahadat/physicsal_navigation

 # <--  The environment constraints for the package.
# محدودیت‌های محیطی برای پکیج.
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

# The dependencies that the package needs to function.
# وابستگی‌هایی که پکیج برای عملکرد صحیح به آن‌ها نیاز دارد.
dependencies:
  flutter:
    sdk: flutter

# Dependencies used only for development and testing.
# وابستگی‌هایی که فقط برای توسعه و تست استفاده می‌شوند.
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  fake_async: ^1.3.1
# Flutter specific configuration.
# تنظیمات اختصاصی فلاتر.
# flutter:
  # This package does not have any specific assets or fonts to declare.
  # این پکیج هیچ دارایی یا فونت خاصی برای تعریف کردن ندارد.